- hosts: k3s
  become: yes

  tasks:
    - name: Installer k3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Attendre que k3s soit prêt
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        timeout: 60

    - name: Récupérer le kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./k3s.yaml
        flat: yes
