Vagrant.configure("2") do |config|
  # Configuration commune (RAM, CPU, Box)
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  # VM 1 : k3s
  config.vm.define "default" do |default|
    default.vm.network "private_network", ip: "192.168.56.10"
    default.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl
    SHELL
  end

  # VM 2 : monitoring
  config.vm.define "monitoring" do |mon|
    mon.vm.network "private_network", ip: "192.168.56.11"
    mon.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl
    SHELL
  end
end
